project_id = "vgiaryswrjuyczgfbany"

[functions.newsletter-signup]
verify_jwt = false

[functions.contact-form]
verify_jwt = false

[functions.free-resources]
verify_jwt = false

[functions.secure-download]
verify_jwt = false

[functions.welcome-email]
verify_jwt = false