// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgiaryswrjuyczgfbany.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnaWFyeXN3cmp1eWN6Z2ZiYW55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NjA0NjQsImV4cCI6MjA3MjEzNjQ2NH0.pf0FKWk7UemuwxuiYC7ATnCTPGTBdjIW0HRIKHjmAxU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});